// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"
	moviedb "ticketing/business/moviedb"

	mock "github.com/stretchr/testify/mock"

	movies "ticketing/business/movies"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Check provides a mock function with given fields: ctx, id
func (_m *Repository) Check(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *Repository) GetByID(ctx context.Context, id int) (movies.Domain, error) {
	ret := _m.Called(ctx, id)

	var r0 movies.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int) movies.Domain); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(movies.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Search provides a mock function with given fields: ctx, title
func (_m *Repository) Search(ctx context.Context, title string) ([]movies.Domain, error) {
	ret := _m.Called(ctx, title)

	var r0 []movies.Domain
	if rf, ok := ret.Get(0).(func(context.Context, string) []movies.Domain); ok {
		r0 = rf(ctx, title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]movies.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, data
func (_m *Repository) Store(ctx context.Context, data *moviedb.Domain) error {
	ret := _m.Called(ctx, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *moviedb.Domain) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
