// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"
	moviedb "ticketing/business/moviedb"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetMovies provides a mock function with given fields: ctx, search
func (_m *Repository) GetMovies(ctx context.Context, search string) ([]moviedb.Domain, error) {
	ret := _m.Called(ctx, search)

	var r0 []moviedb.Domain
	if rf, ok := ret.Get(0).(func(context.Context, string) []moviedb.Domain); ok {
		r0 = rf(ctx, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]moviedb.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, search)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
